### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by JoelSjogren** [susam/mathb#12] opened 2017-04-24 15:27 UTC
`$T^*_{ij} = \overline{T_{ji}}$` does not compile.

`$T_{ij} = \overline{T_{ji}}$` does compile.

**Comment by susam** [comment] 2022-10-08 00:39
Closing this as duplicate of issue #8. Please see issue #8 for resolution notes.

**Closed by susam** 2022-10-08 00:39 UTC
